Support lists of models
zmievsa/cadwyn pull request #241
Opened 2024-12-13 23:46 UTC by kurtmckee

This PR allows routes to be annotated with:

```python
@router.get("/things")
def get_things() -> list[Thing]:
    ...
```

Fixes #240

2024-12-13 23:56 UTC, kurtmckee commented
As noted in #240, this may not be an ideal solution; for example, each iterated call to `self._migrate_response()` creates a new `ResponseInfo` instance, which is immediately discarded because only its `.body` is needed.

It's possible that the conversion work could be done by a helper method, so that it's not `self._migrate_response()` that's getting called.

Please let me know if this is even desirable work, and if you'd like to see an improvement in the design here. :+1:

2024-12-14 17:01 UTC, zmievsa requested changes
Nice work! Just a few small comments from my side

2024-12-14 17:01 UTC, zmievsa commented on cadwyn/structure/versions.py
> +        if isinstance(head_response_model, types.GenericAlias) and isinstance(response_info.body, Sequence):
Does it make sense to use Sequence instead of list here? I can't seem to think of a usecase that would warrant Sequence instead of list

2024-12-14 17:01 UTC, zmievsa commented on tests/test_data_migrations.py
> +        return {"thing": True}  # pyright: ignore[reportReturnType]
I think, we should fix the error as well

2024-12-14 17:01 UTC, zmievsa commented on tests/test_data_migrations.py
> +    instruction = schema(Thing).field("thing").had(type=typing.Literal["yes", "no"])
Nice idea for the test!

2024-12-14 17:01 UTC, zmievsa commented on tests/test_data_migrations.py
> +        return [{"thing": True}]  # pyright: ignore[reportReturnType]
```suggestion
    @router.get("/things", response_model=list[Thing])
    async def get_things()
        return [{"thing": True}]
```

2024-12-16 21:38 UTC, kurtmckee commented on cadwyn/structure/versions.py
> +        if isinstance(head_response_model, types.GenericAlias) and isinstance(response_info.body, Sequence):
I couldn't either, but I saw that `isinstance(..., Sequence)` checks were already in use elsewhere in the file, so I thought that might be the desired formulation.

I'll switch this to `list`.

2024-12-16 21:47 UTC, kurtmckee commented
I want to test one or two additional items before this merges (if it's a desirable change); I'm particularly interested in this use case:

```python
class Thing(BaseModel):
    ...


class TopLevel(BaseModel):
    things: list[Thing]  # <-- Will this get converted?
```

I anticipate that returning a JSON array (instead of an object) may be a niche use case, but I bumped into that while preparing a rough-cut tech demo to present in my workplace, which is how I got to this PR.

2024-12-16 23:41 UTC, kurtmckee commented
Hmm, this doesn't address the more common case that I described above. I think that responding with JSON arrays may be too niche a use case to incorporate into cadwyn.

If you think this PR is valuable, you're welcome to merge it. However, I recommend closing.

I'll work to submit a PR that allows nested objects to be converted, which is far and away the more common case that I expect to use at work. However, I'll open an issue first to document the target work.

2024-12-18 00:07 UTC, closed without merging