check for http method strings in endpoint instruction factory, Closes #78
zmievsa/cadwyn pull request #79
Opened 2023-11-16 17:15 UTC by m0n0x41d

2023-11-16 23:01 UTC, zmievsa requested changes
Thanks for your PR!
Please, update the changelog and fix the comments.

2023-11-16 23:01 UTC, zmievsa commented on tests/test_structure.py
> +        endpoint("/test", ["DEATH", "STRAND"], func_name="Nofunc")
No need to pass func_name.

2023-11-17 06:20 UTC, zmievsa commented
Please, use proper names for both the branch and the pull request. There is no need to add issue name to your pull request. Instead, you should attach PR to issue in the development section by hand.
![image](https://github.com/zmievsa/cadwyn/assets/17561586/c88c2ac3-92ea-48a4-84c3-9193f2661d93)

2023-11-17 15:50 UTC, m0n0x41d commented on tests/test_structure.py
> +        endpoint("/test", ["DEATH", "STRAND"], func_name="Nofunc")
done here!

2023-11-17 16:54 UTC, zmievsa submitted a review, later dismissed
Great job. Thanks!

2023-11-17 17:00 UTC, zmievsa approved these changes

2023-11-17 17:01 UTC, merged